from django.conf import settings

GET_FULL_RESPONSE = 'all'

# Debug for api is set to False by default
DEBUG = False

# Get settings debug value
if settings.DEBUG:
    DEBUG = True

try:
    # As api urls are autogenerated as soon as a new app is added in API_ENABLED_APP which may or may not be unwanted.
    # This keyword is used as pattern blocker and need NOT TO BE CHANGED.
    # But can be changed from "block" to something else
    # Again, doing this is doesn't make any sense.

    URL_PATTERN_BLOCKER = settings.URL_PATTERN_BLOCKER
except AttributeError:
    URL_PATTERN_BLOCKER = 'block'

try:
    # App Endpoints shows only 10 results by default to prevent overloading of server by unwanted computation.
    # This number can be altered by defining a variable in settings.py named ENDPOINT_RESPONSE_LENGTH
    # Set this variable to any number or set it to "all" to show all results by default.

    RESPONSE_LENGTH = settings.RESPONSE_LENGTH
except AttributeError:
    RESPONSE_LENGTH = 10

try:
    # APPS on which REST api is enabled defined as dict in settings.py
    # for ex:
    # API_ENABLED_APPS = {
    #                       'app name here': 'model_here'
    #                  }
    # -->> The "model_here" is the class name which you made in your app.models.

    API_ENABLED_APPS = settings.API_ENABLED_APPS
except AttributeError:
    API_ENABLED_APPS = {}

try:
    # URL defined by you in your settings.py as:
    # It is a dict containing keys as app name and pattern as values.
    # You can define multiple patterns for one app in a list.
    # API_URLS = {
    #               'Model name as key': [
    #                                     'url pattern 1 as value',  -->>   "users/<int:userid>/"
    #                                     'url pattern 2 as value',  -->>   "users/<int:userid>/posts/"
    #                                       ...
    #                                 ]
    #           }
    # You can also block the default API URL access by writing "block" in pattern. For ex : 
    # API_URLS = {
    #               'Model name as key': [
    #                                     "block"
    #                                 ]
    #           }
    # NOTE : This will not effect or block you from accessing that page. It's only for api.
    # URL patterns will be generated automatically for each pattern specified.
    # Everytime u run server, u can see URL patterns being printed in terminal to confirm they are made correctly.

    API_URLS = settings.API_URLS
except AttributeError:
    API_URLS = {}

try:
    # User app may have other model associated with it, for ex: profile, posts, etc..
    # To include those models into the results while requesting user's details, specify which model is
    # associated with user model.
    # Define a list of models in settings.py named USER_RELATED_MODELS and specify models
    # which are related to user model

    USER_RELATED_MODELS = settings.USER_RELATED_MODELS
except AttributeError:
    USER_RELATED_MODELS = []

# Too many try/excepts huh? ... xD
# This is because I wanted to provide detailed information here also... :)
